name: Lumen Check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  payany-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.development', '.env');"
      - name: Lint PHP code
        run: |
          sudo npm config set unsafe-perm=true
          sudo npm i -g phplint
          phplint 'app/**'
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage
      - name: Create Database
        run: touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite
