name: PayAny Check

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  payany-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - name: Start MySQL
        run: |
          sudo systemctl start mysql.service
          mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS oraculo_test';
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Lint PHP code
        run: |
          sudo npm config set unsafe-perm=true
          sudo npm i -g phplint
          phplint 'app/**'
      - name: Install Dependencies
        run: |
          composer update
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Directory Permissions
        run: chmod -R 777 storage/
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: vendor/bin/phpunit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
